# Generated by Django 3.0.8 on 2023-01-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecs_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicinfo',
            name='language',
            field=models.TextField(default='English'),
        ),
    ]
